opennmt/config.py
opennmt/tests/config_test.py

Top level keys are not necessarily dictionaries.
Fixes #8.

Fix configuration file override

---

config/models/transformer.py
config/optim/adam_with_noam_decay.yml
opennmt/decoders/self_attention_decoder.py
opennmt/encoders/self_attention_encoder.py
opennmt/models/transformer.py
opennmt/utils/decay.py
opennmt/utils/transformer.py

This makes the implementation closer to the configuration used in "transformer_base" in Tensor2Tensor.
In particular:
* the decoder only attends the final encoder output
* the layer normalization is moved to the block inputs
* the output of the encoder and decoder is also normalized
* a dropout is applied in the feed forward layer
* the learning rate can be used as a scale factor in the Noam decay

Upgrade the Transformer model

---

.gitmodules
.travis.yml
CMakeLists.txt
README.md
bin/build_vocab.py
bin/detokenize_text.py
bin/tokenize_text.py
config/sample.yml
config/tokenization/aggressive.yml
config/tokenization/sample.yml
docs/data.md
docs/index.rst
docs/package/opennmt.tokenizers.opennmt_tokenizer.rst
docs/package/opennmt.tokenizers.rst
docs/tokenization.md
opennmt/inputters/text_inputter.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/tokenizer_test.py
opennmt/tokenizers/__init__.py
opennmt/tokenizers/opennmt_tokenizer.py
opennmt/tokenizers/tokenizer.py
opennmt/utils/evaluator.py
opennmt/utils/misc.py
opennmt/utils/vocab.py
third_party/learn_bpe.py

This PR adds advanced tokenization by using OpenNMT's [Tokenizer](https://github.com/OpenNMT/Tokenizer) as a plugin. It also adds the detokenization logic when saving inference or evaluation predictions.
Closes #24.

Advanced tokenization

---

opennmt/inputters/inputter.py
opennmt/inputters/record_inputter.py
opennmt/inputters/text_inputter.py
opennmt/models/model.py
opennmt/models/sequence_classifier.py
opennmt/models/sequence_tagger.py
opennmt/models/sequence_to_sequence.py

When the `sample_buffer_size` is small compared to the training data size and the evaluation frequency is high, the training will consistently miss a portion of the dataset.
This change randomly selects a shard of the dataset to ensure that the full dataset can be seen during the training.

Shard the dataset for small sample buffer sizes

---

bin/ark_to_records.py
config/models/nmt_medium_fp16.py
config/models/transformer_fp16.py
opennmt/decoders/decoder.py
opennmt/decoders/rnn_decoder.py
opennmt/decoders/self_attention_decoder.py
opennmt/encoders/rnn_encoder.py
opennmt/inputters/inputter.py
opennmt/inputters/record_inputter.py
opennmt/inputters/text_inputter.py
opennmt/models/model.py
opennmt/models/sequence_classifier.py
opennmt/models/sequence_tagger.py
opennmt/models/sequence_to_sequence.py
opennmt/models/transformer.py
opennmt/utils/losses.py
opennmt/utils/position.py

This makes all operations using the dtype defined by the inputter and allows using, e.g., FP16 models.
Related to #57.

Inherit dtype from the inputter

---

README.md
bin/main.py
config/sample.yml
opennmt/runner.py

This PR adds 2 run types:
* `train`: runs the training
* `eval`: runs the evaluation
The current `train` behavior is now `train_and_eval` for clarity.

Allow split training end evaluation runs

---

config/models/listen_attend_spell.py
opennmt/inputters/record_inputter.py

This makes training on record files more convenient as there is now no need to specify the depth dimension in the configuration file.

Infer records depth dimension by peeking the records file

---

opennmt/models/model.py
opennmt/models/sequence_classifier.py
opennmt/models/sequence_tagger.py
opennmt/models/sequence_to_sequence.py
opennmt/models/transformer.py
opennmt/utils/parallel.py

Models containing dynamic loops (e.g. RNNs) are not compatible with this custom variable getter so disable it by default for models where RNNs can be used (currently all except the Transformer).
Closes #74.

Disable the daisy chain custom getter for non Transformer models

---

CHANGELOG.md
README.md
examples/cpp/README.md
examples/serving/README.md
opennmt/decoders/rnn_decoder.py
opennmt/models/model.py
opennmt/runner.py
opennmt/utils/beam_search.py
opennmt/utils/losses.py
setup.py

For compatibility with TensorFlow 1.4 (last version compiled against CUDA 8), you can stay on the `r1` branch.

Update minimum required TensorFlow version to 1.6

---

bin/ark_to_records.py
opennmt/config.py
opennmt/inputters/text_inputter.py
opennmt/runner.py
opennmt/tests/config_test.py
opennmt/tests/inputter_test.py
opennmt/tokenizers/tokenizer.py
opennmt/utils/evaluator.py
opennmt/utils/hooks.py

changed all instances of open to io.open (with encoding="utf-8"), unless byte mode is set

Use io.open instead of open for Python 2.7 compatibility

---

.travis.yml
CHANGELOG.md
README.md
examples/serving/README.md
opennmt/decoders/rnn_decoder.py
opennmt/models/model.py
opennmt/runner.py
opennmt/utils/beam_search.py
opennmt/utils/losses.py
setup.py

The code on `master` was using very few new features from the latest TensorFlow versions. So let's avoid breaking compatibility with 1.4 and 1.5 for now but still use newer arguments or functions when available.

Relax TensorFlow version requirement

---

.gitmodules
.travis.yml
CHANGELOG.md
CMakeLists.txt
config/tokenization/sample.yml
docs/tokenization.md
opennmt/tests/tokenizer_test.py
opennmt/tokenizers/opennmt_tokenizer.py
setup.py

This PR uses the recently released Python package of the OpenNMT Tokenizer to avoid a manual and cumbersome compilation.

Use latest pyonmttok package

---

CHANGELOG.md
opennmt/decoders/decoder.py
opennmt/decoders/rnn_decoder.py
opennmt/decoders/self_attention_decoder.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/decoder_test.py

Starting from TensorFlow 1.8, alignment history can be returned when using a standard `AttentionalRNNDecoder` in both greedy and beam search.
Closes #2.

Return alignment history when decoding from an AttentionalRNNDecoder

---

CHANGELOG.md
opennmt/layers/reducer.py
opennmt/tests/reducer_test.py

The reduction failed when the maximum sequence length was lower than the tensors time dimension.

Fix reduction of sequences with extra padding

---

CHANGELOG.md
opennmt/encoders/encoder.py
opennmt/tests/encoder_test.py

As used in the "Cascaded Encoder" of https://arxiv.org/abs/1804.09849.

Support transition layers in SequentialEncoder

---

scripts/wmt/README.md

I noticed a typo and thought that fixing it would be a good practical intro (after reading CONTRIBUTING.md) to OpenNMT-tf, a project that looks very promising to me.
Test plan:
Given that this commit deals with documentation, I have conducted visual testing.

Fix a typo in scripts/wmt/README.md

---

CHANGELOG.md
README.md
config/models/transformer_fp16.py
config/sample.yml
docs/package/opennmt.optimizers.mixed_precision_wrapper.rst
docs/package/opennmt.optimizers.rst
docs/training.md
opennmt/decoders/self_attention_decoder.py
opennmt/encoders/self_attention_encoder.py
opennmt/layers/transformer.py
opennmt/models/catalog.py
opennmt/models/model.py
opennmt/optimizers/__init__.py
opennmt/optimizers/mixed_precision_wrapper.py
opennmt/utils/optim.py

Enable mixed precision training for Transformer models

---

opennmt/decoders/decoder.py
opennmt/inputters/text_inputter.py
opennmt/layers/position.py

This change introduced in e3e006c6 was required when Adafactor crashed
on sparse updates. The fallback to dense gradients is now implemented
in the optimizer itself.

Revert usage of embedding_lookup wrapper

---

CHANGELOG.md
opennmt/inputters/text_inputter.py
opennmt/tests/inputter_test.py

This fixes issues when the vocabulary is stored in the model directory or when the model uses a joint vocabulary.

Name projector metadata file with the embedding variable name

---

opennmt/decoders/self_attention_decoder.py

when memory is None, add the else clause and set: `context = encoded`
and add `if last_attention is not None:`
It can be used to build bi-directional self-attention decoder (which memory is None) for the Masked LM Task.

set context = encoded when memory is None

---

CHANGELOG.md
opennmt/models/model.py

This class currently infers the input depth from the training data. However, this code was not invoked when exporting the inputs for serving.
As a workaround, if the training data is found in the configuration at export time, the depth detection code is called.
Fixes #289.

Workaround model export error on SequenceRecordInputter

---

CHANGELOG.md
opennmt/decoders/decoder.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/decoder_test.py
opennmt/tests/sequence_to_sequence_test.py

* During guided alignment, we should constrain the alignments of  "a b c" and not "\<s> a b c".
* During decoding, we should return the alignments of "a b c" and not  "\<s> a b".

Fix offset in alignment vectors

---

docs/configuration_reference.md
docs/tokenization.md
opennmt/inputters/inputter.py
opennmt/inputters/text_inputter.py
opennmt/tests/inputter_test.py
opennmt/tokenizers/__init__.py

In particular, do not require to change the model definition to configure the tokenization.

Simplify configuration of on-the-fly tokenization

---

CHANGELOG.md
opennmt/models/language_model.py
opennmt/models/model.py
opennmt/models/sequence_to_sequence.py

This iterates on ea72cb3 to correctly better handle stateful layers.
Fixes #371.

Do not rebuild input and output layers under reused scope

---

CHANGELOG.md
opennmt/models/language_model.py

Some stateful layers like PositionEmbedder recreates their variables unless the scope is marked for reuse.
Fixes #377.

Mark variable scope for reuse in LM inference

---

CHANGELOG.md
opennmt/inputters/inputter.py

Mark MultiInputter as built when all children are built

---

opennmt/utils/data.py

TensorFlow 1.14 changed the behavior of group_by_window that now receives a DatasetV2 instance.

Use tf.data.get_output_shapes when available

---

docs/configuration.md
opennmt/models/sequence_to_sequence.py
opennmt/runner.py
opennmt/tests/model_test.py

Default to returning the best hypothesis only (like command line inference does) and read params/num_hypotheses and infer/n_best to set the number of returned hypotheses.

Fix unexpected number of hypotheses returned by exported models

---

opennmt/layers/noise.py
opennmt/tests/noise_test.py

Returns `tf.identity(words)` if there is only one word.
Currently in master, if `num_words` equals 1 and that word is selected for dropout, `tf.random.uniform([1], maxval=num_words - 1, dtype=tf.int64)` in line 154  throws an error, `Invalid argument: Need minval < maxval, got 0 >= 0`. Return early so this line won't error and at least 1 word is always returned.
Here's a snippet of my stacktrace when I run `onmt-main train_and_eval ...`:
```
File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: Need minval < maxval, got 0 >= 0
[[node transformer/map/while/cond/random_uniform (defined at …
```

Dont dropout if only 1 word

---

opennmt/models/language_model.py

Currently, the step counter starts at zero in `decoding.dynamic_decode`, even when decoding from context with a language model, which I think may lead to positional encodings being off with Transformer language models.
I've tried to provide a fix for this here, not sure if it's the correct way to go about it.

Add offset to step when generating from context with language model

---

opennmt/evaluation.py
opennmt/tests/evaluation_test.py

The improvement should be checked against the steps-1 value only.

Fix early stop logic

---

docs/configuration.md
opennmt/models/sequence_to_sequence.py

Currently user's are allowed to set the decoding_subword_token parameter to any custom value, but are not able to specify whether this should be interpreted as a joiner, or a spacer. The current approach works for standard BPE or SentencePiece but does not facilitate experimentation with custom subtokenization packages. 
In this PR we enable this option while defaulting to previous behaviour to maintain backwards compatibility.
This is necessary for our team that uses custom tokenisation and we would prefer to merge into upstream rather than maintain our own fork. I hope that the proposed change doesn't break anyone's workflow while providing extra flexibility for others as well. In case it matters, this a public mirror our [tokenisation library](https://github.com/kovalevfm/SubTokenizer)

Allow user's to override default subword token assumption 

---

opennmt/data/vocab.py
opennmt/tests/vocab_test.py

New word embeddings should be initialized to a distribution that is close to the original variable otherwise this could lead to exploding gradients.

Mirror variables distribution when updating vocabulary

---

examples/serving/tensorflow_serving/README.md
examples/serving/tensorflow_serving/docker/build_tensorflow_serving.sh
examples/serving/tensorflow_serving/docker/serving_dockerfile.patch
examples/serving/tensorflow_serving/docker/tfaddons_beam_search_ops.patch
examples/serving/tensorflow_serving/requirements.txt

The `Addons>GatherTree` op is currently not included in the official TensorFlow Serving builds. This custom image should unblock users that are already looking to use Serving with OpenNMT-tf v2 models.

Use custom TensorFlow Serving image to support beam search

---

docs/configuration.md
opennmt/inputters/__init__.py
opennmt/inputters/inputter.py
opennmt/inputters/text_inputter.py
opennmt/models/language_model.py
opennmt/models/model.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/inputter_test.py
opennmt/tests/model_test.py
opennmt/tests/test_util.py

This is especially needed for language models where these special tokens may or may not be wanted depending on the task requirement.
For example, to allow nonconditional and unbounded generation of text, one would enable `<s>` but disable `</s>`. However, to generate a fixed sequence from a prefix/context, one would disable `<s>` but enable `</s>`.
This change also enables this configuration for seq2seq models (source and target). There could be reasons to want `</s>` at the end of the source sequences.

Make injection of special sequence tokens (<s>, </s>) configurable

---

opennmt/runner.py
opennmt/tests/runner_test.py

The documentation of `experimental_distribute_dataset` says:
> We will assume that the input dataset is batched by the global batch size. With this assumption, we will make a best effort to divide each batch across all the replicas (one or more workers).
So we need to scale the batch size by the requested number of training devices.

Fix batch size in multiple GPU training

---

opennmt/models/catalog.py

Fix super() call in LstmCnnCrfTagger.auto_config

---

opennmt/models/model.py

If build() was called by the user, we can't guarantee that all variables have been created.

Do not skip variable creation after build() was called

---

opennmt/tests/checkpoint_test.py
opennmt/tests/misc_test.py
opennmt/utils/checkpoint.py
opennmt/utils/misc.py

The previous logic incorrectly assumes how TensorFlow generates variables name in the checkpoint. We now invoke a TensorFlow API to deduce the mapping between variables and their name in the checkpoint.

Fix retrieval of variable from object-based name in checkpoint averaging

---

opennmt/optimizers/utils.py

This property was removed in https://github.com/tensorflow/tensorflow/commit/d02266ff21959e08b875cfb92477e0e865140aaa.

Do not use device_map to get the replica variable

---

opennmt/training.py

https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/models/sequence_classifier.py#L61
In SequenceClassifier, the compute_loss returns a tuple of length 2.

Fix reporting loss bug

---

opennmt/data/__init__.py
opennmt/data/dataset.py
opennmt/inputters/inputter.py
opennmt/runner.py
opennmt/tests/dataset_test.py
opennmt/training.py

This handles the case of a finite dataset more nicely. This change also prepares the dataset sharding for multi-worker training.

Make dataset cardinality a multiple of the number of replicas

---

docs/configuration.md
opennmt/inputters/text_inputter.py
opennmt/tests/runner_test.py

This was the behavior in V1 but was temporarily disabled in V2 due to a TensorFlow bug.
A new export_vocabulary_assets parameters can be used to include vocabularies in the graph itself (behavior in V2 before this commit).
Closes #516.

Export vocabularies as assets by default

---

opennmt/decoders/decoder.py
opennmt/decoders/self_attention_decoder.py
opennmt/utils/decoding.py

The memory_kv cached projections do not need to be reordered as they are the same for all beams.

Avoid unnecessary state reodering during beam search

---

opennmt/models/model.py

Some models may not need to run some initialization after the constructor.

Do not require call to Model.initialize

---

opennmt/bin/main.py

We inject a dummy option to prevent the run type to be treated as a value of the --config option.

Fix command line parsing when --config is used before the run type

---

scripts/wmt/prepare_data.sh

`third_party` directory not included anymore (since `r2`?)

fix input-from-sgm.perl fetch

---

setup.py

mecab-python3 does not provide packages for Windows.

Pin sacrebleu to last version without the mecab-python3 dependency

---

opennmt/data/dataset.py
opennmt/inputters/inputter.py
opennmt/models/language_model.py

slight refactoring of training/inference pipeline to accept more generically a list of transformation function. keep existing parameters for API backward compatibility. 
This PR is needed for #635.

refactor process_fn to be more generic through transform_fns

---

setup.py

This version removed the `mecab-python3` dependency which was not available on Windows.
Related to #653.

Update sacrebleu to 1.4.9

---

opennmt/data/dataset.py
opennmt/inputters/__init__.py
opennmt/inputters/inputter.py
opennmt/models/language_model.py

This removes the duplicated code between `ExampleInputter` and `LanguageModelInputter` that we frequently forgot to keep in sync. Now an adapter class can build evaluation and training datasets for both supervised and unsupervised examples.

Factorize eval and train datasets construction from inputters

---

opennmt/inputters/inputter.py

They were removed in e5dac9190e59d2b3dc1fa697018a915ac22df601 but they are required for sequence bucketing and token-based batching.

Add missing length functions arguments

---

opennmt/data/dataset.py
opennmt/inputters/inputter.py
opennmt/inputters/text_inputter.py
opennmt/utils/misc.py

The generic way to compute the dataset size is to iterate over it. This is relatively slow. This change adds a faster code path for text training files where counting the number of lines is trivial.

Faster dataset size computation for text training files

---

opennmt/runner.py
opennmt/tests/misc_test.py
opennmt/utils/misc.py

In case the inference dataset is bucketized, no output can be written for a long period of time. With this change we log something regularly to not give the impression that the process is stuck.

Add more logs during inference to avoid confusion

---

opennmt/bin/main.py
opennmt/utils/__init__.py
opennmt/utils/exporters.py

Like tokenizers, scorers, etc., this allows registering custom exporters in user code.

Add a registry of exporters

---

docs/generate-apidoc.py

Some free functions actually point to methods.

Fix missing functions in API docs

---

opennmt/bin/main.py
opennmt/config.py
opennmt/models/catalog.py
opennmt/runner.py
opennmt/tests/config_test.py
opennmt/tests/runner_test.py

Calling `deepcopy` on a RNN model broke in TensorFlow 2.2. In general, it seems this is something we should avoid. In this change, we pass a model function to the `Runner` class so that it can build new model instances on demand.
This is a partial workaround for the issue described in https://github.com/OpenNMT/OpenNMT-tf/issues/672 as it only fixes the error for users training with `onmt-main` but not for users of the `Runner` class.
Fixes #672.

Avoid deepcopying the model instance

---

docs/data.md
opennmt/inputters/inputter.py
opennmt/tests/inputter_test.py

This is needed when passing data files for nested inputs on the command line, where there is no easy way to represent a nested structure.

Allow passing a flat list of files to nested inputters

---

examples/serving/python/ende_client.py
examples/serving/tensorflow_serving/README.md

Exported models no longer include a custom TensorFlow op.

Update serving examples based on the latest model export

---

opennmt/tests/runner_test.py
opennmt/training.py

Prior to this change, a warning was logged if the training end conditions are met before starting the training loop. However, it is a
bit unexpected for the user that the training terminates without errors but no iterations are executed.
The error messages have been updated with the actions required to make the training continue.

Raise errors when starting the training but end conditions are met

---

opennmt/inputters/inputter.py
opennmt/inputters/text_inputter.py
opennmt/models/language_model.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/inputter_test.py
opennmt/tests/misc_test.py
opennmt/utils/misc.py

`asset_prefix` is used to differentiate resources used by parallel inputters.
The goal of this change is to allow inputters to read the data configuration as if there was no prefix. Ideally they should not know
that they are used with other inputters.
Now the `asset_prefix` attribute is correctly set for all parallel inputters and the data configuration is wrapped to allow making
relative lookups (e.g. "vocabulary" will resolve to "source_vocabulary").

Cleanup asset prefix generation and usage

---

opennmt/tests/misc_test.py
opennmt/utils/checkpoint.py
opennmt/utils/exporters.py
opennmt/utils/misc.py

The implementation is now more robust when variables are wrapped by an additional class (e.g. MirroredVariable, AutoCastVariable, etc.).

Improve resolution of variable name in the checkpoint

---

opennmt/tests/training_test.py
opennmt/training.py
opennmt/utils/misc.py

There is no need to get the primary variable to make it work. The update should be run under the distributed strategy scope.

Cleanup moving average for mirrored variables

---

opennmt/config.py

This message is frequently interpreted as an error by users. If the user changed the model, there will be an error when loading the
checkpoint anyway.

Remove warning about changing the model when a checkpoint exists

---

docs/configuration.md
opennmt/models/model.py

This was removed in OpenNMT-tf V2 but it can be useful in some cases.

Add decay_step_duration parameter

---

opennmt/bin/build_vocab.py
opennmt/tokenizers/opennmt_tokenizer.py

When training a SentencePiece model from a pre-tokenization, we can't simply reuse the vocabulary generated by SentencePiece. We should tokenize the data with the trained SentencePiece model and build the vocabulary from that.

Fix vocabulary when using SentencePiece with pre-tokenization

---

docs/configuration.md
opennmt/inputters/inputter.py
opennmt/models/sequence_classifier.py
opennmt/models/sequence_tagger.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/losses_test.py
opennmt/tests/model_test.py
opennmt/utils/losses.py

Accept an additional file with weights that are used to scale the loss of their corresponding sentence. See also https://github.com/OpenNMT/OpenNMT-py/pull/1438.
Since loading this additional file is similar to how we currently load the alignments for guided alignment, this PR adds a generic framework to load training data annotations.

Add sentence weighting

---

docs/configuration.md
docs/serving.md
docs/training.md
opennmt/evaluation.py

Still accept `external_evaluators` for backward compatibility.

Rename parameter external_evaluators to scorers

---

opennmt/decoders/self_attention_decoder.py
opennmt/encoders/self_attention_encoder.py
opennmt/layers/transformer.py
opennmt/models/transformer.py

While there is probably no need to disable the current pre-norm, this flag offers this possibility and makes it clearer that the default
architecture is different from the original Transformer paper.

Add flag to disable pre-norm and enable post-norm Transformer architecture

---

docs/serving.md
opennmt/bin/main.py

Still accept previous option names for backward compatibility.

Do not repeat "export" in export command line options

---

opennmt/config.py
opennmt/tests/tokenizer_test.py
opennmt/tokenizers/tokenizer.py
setup.py

The unsafe loader is able to create arbitrary Python object, but this is not something we need.

Use safe API when loading YAML configuration

---

opennmt/models/sequence_to_sequence.py
opennmt/tests/tflite_test.py

Since this method is not calling the model `__call__` entrypoint, it should call `build()` by itself.
See https://github.com/OpenNMT/OpenNMT-tf/pull/789#issuecomment-788556988

Build model in infer_tflite method

---

.github/workflows/ci.yml
README.md
docs/installation.md
docs/quickstart.md
opennmt/__init__.py
opennmt/version.py
setup.cfg
setup.py
tools/update_version.py

There are multiple official and community TensorFlow packages out there: tensorflow, tensorflow-cpu, tensorflow-gpu, tf-nightly, tensorflow-rocm, intel-tensorflow, tensorflow-macos, etc.
The main "tensorflow" package works in most cases but ultimately we should allow users to install an alternative package.
The TensorFlow version will be checked on import and a warning will be raised if the version is not officially supported.

Remove direct dependency on TensorFlow

---

docs/training.md
opennmt/runner.py
opennmt/tests/runner_test.py
opennmt/tests/test_util.py
opennmt/training.py
opennmt/utils/misc.py

OpenNMT-tf used the "auto_mixed_precision" graph optimization pass to enable mixed precision training. However, the [Keras mixed precision API](https://www.tensorflow.org/guide/mixed_precision) appears to be the recommended API to enable mixed precision training in TensorFlow.

Use Keras mixed precision API instead of auto_mixed_precision

---

opennmt/bin/main.py

The environment variable to configure the TensorFlow C++ logs should be set before running the script. It has no effect after TensorFlow is imported.

Remove C++ logging level that has no effect

---

opennmt/optimizers/utils.py
opennmt/tests/transformer_test.py

Reverts OpenNMT/OpenNMT-tf#825
This was a regression in TensorFlow 2.5 RC that will be fixed in the final release: https://github.com/tensorflow/tensorflow/issues/48430

Revert "Allow non fully defined gradient shape when accumulating gradients"

---

examples/serving/python/ende_client.py

Keep a reference on the loaded model to prevent resources from getting deleted.

Fix error in Python serving example with TensorFlow 2.5

---

opennmt/runner.py

When creating a subprocess, the default behavior is to forward the current environment variables to the child process. But in commit https://github.com/OpenNMT/OpenNMT-tf/commit/80ce857726296acd9280816c4a25f78f3ef41ce4, the `env` argument is explicitly set and so the other variables were no longer forwarded.
Possible fix for #847.

Forward current environment variables when autotuning batch size

---

.github/workflows/ci.yml
docs/tokenization.md
opennmt/tests/tokenizer_test.py
opennmt/tokenizers/__init__.py
opennmt/tokenizers/opennmt_tokenizer.py
opennmt/tokenizers/sentencepiece_tokenizer.py
opennmt/tokenizers/tokenizer.py
setup.py

This tokenizer is implemented as a TensorFlow op so it can be included in the exported graph. It should also be more efficient than the OpenNMT tokenizer when used on-the-fly during the training.

Add SentencePieceTokenizer from tensorflow-text

---

opennmt/tests/runner_test.py
opennmt/utils/decoding.py
opennmt/utils/misc.py

The gather_tree function in TensorFlow Addons is wrapped by a `tf.function`. This should not be an issue, but it appears that the function gets unexpectedly garbage collected when running our test suite.

Copy gather_tree functions from TF Addons to re-enable beam tests

---

setup.py

The package is now available on Linux, macOS, and Windows.

Remove environment markers for pyonmttok package

---

opennmt/models/model.py

The token-level scores are useless if the tokenized target is not available.

Always output the tokenized target in scoring

---

opennmt/models/model.py
opennmt/schedules/lr_schedules.py
opennmt/tests/lr_schedules_test.py

Before this change, `learning_rate` was always passed as the first argument to the schedule constructor. Now, `learning_rate` is not passed if the first argument is already configured in `decay_params`.
Closes #923.

Allow setting all learning rate schedules parameters

---

opennmt/layers/transformer.py

Fix for https://forum.opennmt.net/t/load-a-savedmodel-in-tensorflow/4506/15.

Rollback to tf.nn.embedding_lookup in non TensorFlow Lite mode

---

opennmt/inputters/inputter.py
opennmt/tests/inputter_test.py

We want the length dimension to be unknown when building the graph.

Pad dynamically when preparing the dataset for batch size autotuning

---

opennmt/tests/misc_test.py
opennmt/utils/misc.py

Fix count_lines function when the file is gzipped

---

opennmt/decoders/decoder.py
opennmt/training.py

The reported norm was misleading because it did not take into account gradient accumulation and multi-GPU. Removing this feature for now.

Remove recording of the global gradient norm
