OpenNMT/OpenNMT-tf

opennmt/utils/transformer.py

Moments should be computed along the last axis.
Fixes #1.

Fix the layer normalization used in the Transformer

---

bin/main.py
opennmt/models/sequence_classifier.py
opennmt/models/sequence_tagger.py
opennmt/models/sequence_to_sequence.py
opennmt/utils/misc.py

Check output stream encoding before decoding from bytes

---

opennmt/decoders/rnn_decoder.py

Up to 20% faster when training a RNN decoder.

Fuse RNN decoder projection during training

---

opennmt/decoders/self_attention_decoder.py
opennmt/encoders/self_attention_encoder.py
opennmt/tests/transformer_test.py
opennmt/utils/position.py
opennmt/utils/transformer.py

This PR speeds up the self-attention modules:
* up to 1.8x faster batch training
* up to 8x faster batch inference
Existing models using self-attention modules are no longer compatible.

Optimize transformer speed

---

bin/main.py
config/sample.yml
opennmt/tests/evaluator_test.py
opennmt/utils/evaluator.py
opennmt/utils/hooks.py
third_party/multi-bleu.perl

These evaluators are executed on the **saved** evaluation predictions (with `save_eval_predictions` flag) and report evaluation score in TensorBoard and the shell.
Fixes #5.

Support external evaluators

---

config/sample.yml
opennmt/models/model.py
opennmt/models/sequence_tagger.py
opennmt/models/sequence_to_sequence.py
opennmt/models/transformer.py
opennmt/utils/losses.py

This is the behavior implemented in OpenNMT-lua.

Do not average loss in time by default

---

opennmt/models/sequence_tagger.py

add a identity tensor "length" for predict

---

opennmt/utils/misc.py

Change file read encoding to binary

---

third_party/apply_bpe.py
third_party/learn_joint_bpe_and_vocab.py

I noticed you have added BPE script in the third_party directory. But I think "learn_bpe.py" is just a part of BPE encoding. "apply_bpe.py" can encode can re-apply byte pair encoding with vocabulary filter. more conventiently, you can do the same with "learn_joint_bpe_and_vocab.py".

Add BPE encoding script

---

bin/average_checkpoints.py
docs/index.rst
docs/inference.md

Add checkpoints averaging

---

opennmt/models/model.py
opennmt/utils/hooks.py
opennmt/utils/losses.py

* Revise active variable scope when summarizing a tensor
* Always summarize the token level loss

Cleanup TensorBoard summaries

---

README.md
bin/main.py
docs/package/opennmt.utils.parallel.rst
docs/package/opennmt.utils.rst
docs/training.md
opennmt/models/model.py
opennmt/models/sequence_tagger.py
opennmt/utils/losses.py
opennmt/utils/optim.py
opennmt/utils/parallel.py

This mode replicates the main section of the graph over multiple devices and processed batches in parallel. The resulting graph is equivalent to train with batches `N` times larger, where `N` is the number of used GPUs.
Closes #16.

Support in-graph replication

---

opennmt/decoders/self_attention_decoder.py
opennmt/encoders/self_attention_encoder.py
opennmt/layers/__init__.py
opennmt/layers/position.py
opennmt/models/transformer.py
opennmt/tests/position_test.py

Add sinusoidal position encoding

---

bin/main.py
docs/package/opennmt.rst
docs/package/opennmt.runner.rst
opennmt/__init__.py
opennmt/config.py
opennmt/runner.py

This is a refactoring to move the runs configuration and management inside the library.

Create Runner class to manage training, inference, and export

---

config/sample.yml
opennmt/inputters/inputter.py
opennmt/inputters/record_inputter.py
opennmt/inputters/text_inputter.py
opennmt/models/model.py
opennmt/models/sequence_classifier.py
opennmt/models/sequence_tagger.py
opennmt/models/sequence_to_sequence.py
opennmt/runner.py
opennmt/utils/data.py

This is a fixed version of a4235338.
Fixes #49.

Randomly shard the dataset for small sample buffer sizes

---

scripts/wmt/README.md
scripts/wmt/config/wmt_ende.yml
scripts/wmt/config/wmt_ende_1gpu.yml
scripts/wmt/eval_wmt_ende.sh
scripts/wmt/prepare_data.sh
scripts/wmt/run_wmt_ende_1gpu.sh

* Use the OpenNMT-tf package and do not assume that the script is run
inside the Git repository
* Use default SentencePiece binaries location
* Make `DATA_PATH` a command line argument

Update the WMT scripts

---

CHANGELOG.md
docs/package/opennmt.utils.checkpoint.rst
docs/package/opennmt.utils.rst
opennmt/bin/average_checkpoints.py
opennmt/runner.py
opennmt/utils/checkpoint.py

Expose a function for checkpoints averaging

---

CHANGELOG.md
opennmt/decoders/self_attention_decoder.py
opennmt/layers/transformer.py
opennmt/models/catalog.py
opennmt/models/transformer.py
opennmt/tests/transformer_test.py

As described in [Zhang et al. 2018](https://arxiv.org/abs/1805.00631).

Average attention network in the Transformer decoder

---

CHANGELOG.md
docs/package/opennmt.optimizers.multistep_adam.rst
docs/package/opennmt.optimizers.rst
opennmt/optimizers/__init__.py
opennmt/optimizers/multistep_adam.py

Credits to https://github.com/tensorflow/tensor2tensor/pull/754.
Closes #135.

Adam optimizer that accumulates gradients of multiple steps

---

opennmt/decoders/self_attention_decoder.py
opennmt/layers/transformer.py

Cache split keys and values

---

CHANGELOG.md
opennmt/decoders/rnn_decoder.py

Correctly disable fused projection when using scheduled sampling

---

CHANGELOG.md
opennmt/utils/checkpoint.py

Average checkpoint variables in a float32 array

---

CHANGELOG.md
opennmt/encoders/rnn_encoder.py
opennmt/tests/encoder_test.py

Set input length lower bound to the total reduction factor

---

CHANGELOG.md
opennmt/bin/main.py

Fix path prefixing when the data configuration includes lists

---

CHANGELOG.md
opennmt/bin/main.py
opennmt/config.py
opennmt/inputters/text_inputter.py
opennmt/tokenizers/tokenizer.py
opennmt/utils/misc.py

Use tf.gfile instead of Python's file when approriate

---

CHANGELOG.md
opennmt/models/__init__.py
opennmt/models/sequence_to_sequence.py
opennmt/models/transformer.py

Start by supporting simple source and target sharing.
Related to #143.

Add argument to SequenceToSequence models to share embeddings

---

CHANGELOG.md
config/sample.yml
docs/data.md
opennmt/decoders/decoder.py
opennmt/decoders/rnn_decoder.py
opennmt/decoders/self_attention_decoder.py
opennmt/layers/transformer.py
opennmt/models/model.py
opennmt/models/sequence_to_sequence.py
opennmt/models/transformer.py
opennmt/tests/decoder_test.py
opennmt/tests/sequence_to_sequence_test.py
opennmt/utils/beam_search.py

This PR adds support for guided alignment, specifically for the `SelfAttentionDecoder` as of now. It guides the first attention head of the last layer to produce alignment that can be used during inference.

Guided alignment for SelfAttentionDecoder

---

CHANGELOG.md
README.md
config/sample.yml
docs/configuration.md
opennmt/bin/main.py
opennmt/config.py
opennmt/models/catalog.py
opennmt/models/model.py
opennmt/models/sequence_to_sequence.py
opennmt/models/transformer.py
opennmt/runner.py
opennmt/utils/misc.py
scripts/wmt/README.md
scripts/wmt/config/wmt_ende.yml
scripts/wmt/config/wmt_ende_1gpu.yml
scripts/wmt/eval_wmt_ende.sh
scripts/wmt/run_wmt_ende.sh
scripts/wmt/run_wmt_ende_1gpu.sh

Add flag to use automatic training configuration values

---

CHANGELOG.md
docs/package/opennmt.bin.convert_checkpoint.rst
docs/package/opennmt.bin.rst
opennmt/bin/convert_checkpoint.py
opennmt/tests/checkpoint_test.py
opennmt/utils/checkpoint.py
setup.py

Add script to convert checkpoint data type

---

CHANGELOG.md
opennmt/decoders/__init__.py
opennmt/decoders/rnn_decoder.py
opennmt/tests/decoder_test.py

Add the RNMT+ decoder

---

opennmt/decoders/decoder.py
opennmt/layers/transformer.py
opennmt/optimizers/adafactor.py
opennmt/tests/data_test.py
opennmt/utils/beam_search.py
opennmt/utils/data.py

Other numerical cast ops will be removed in TensorFlow 2.0.

Update all cast ops to use tf.cast

---

CHANGELOG.md
docs/configuration_reference.md
opennmt/models/model.py
opennmt/models/sequence_to_sequence.py
opennmt/runner.py
opennmt/tests/data_test.py
opennmt/tests/misc_test.py
opennmt/utils/data.py
opennmt/utils/misc.py

This increases the translation efficiency as similar source lengths have similar target lengths, which reduces the overall computation time spent on padding tokens.

Support sorting inference data by lengths

---

CHANGELOG.md
opennmt/decoders/decoder.py
opennmt/tests/decoder_test.py

(And add a test for it.)
Fixes #266.

Fix variable creation order mismatch when using a DenseBridge

---

CHANGELOG.md
opennmt/tests/checkpoint_test.py
opennmt/utils/checkpoint.py

Save merged vocabularies

---

CHANGELOG.md
opennmt/utils/data.py

Do not bucketize dataset with parallel inputs

---

CHANGELOG.md
opennmt/models/sequence_to_sequence.py

Fix batch size definition in case of parallel encoders

---

opennmt/runner.py

Some tasks (e.g. scoring) do not require an Estimator instance. Additionally, we sometimes need to run task-specific code before creating the Estimator.

Only create Estimator when needed

---

opennmt/models/model.py
opennmt/utils/hooks.py

* Do not save counter variable in checkpoints
* Use source/target terminology instead of features/labels

Cleanup words per second hook

---

config/models/transformer_shared_embedding.py
opennmt/inputters/inputter.py
opennmt/inputters/text_inputter.py
opennmt/layers/__init__.py
opennmt/layers/common.py
opennmt/models/model.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/common_layers_test.py
opennmt/tests/inputter_test.py
opennmt/utils/beam_search.py
opennmt/utils/misc.py

Save embeddings as attributes for easier sharing

---

CHANGELOG.md
docs/configuration.md
opennmt/models/sequence_tagger.py

Allow configuring tagging_scheme in the data configuration

---

CHANGELOG.md
opennmt/models/sequence_to_sequence.py
opennmt/tests/model_test.py

Fix dimension mismatch when using replace_unknown_target

---

CHANGELOG.md
opennmt/layers/bridge.py
opennmt/layers/position.py
opennmt/utils/compat.py

Do not rebuild stateful layers under variable scopes with reuse

---

CHANGELOG.md
opennmt/inputters/inputter.py

Mark shared inputters as built

---

CHANGELOG.md
opennmt/estimator.py
opennmt/runner.py

Fix error during manual model export

---

CHANGELOG.md
opennmt/models/sequence_to_sequence.py

Explicit reshape dimension in case the alignment vector is empty

---

opennmt/models/sequence_to_sequence.py

Fix typo in SequenceToSequence output layer dtype

---

CHANGELOG.md
opennmt/utils/hooks.py

Do not create new ops in LoadWeightsFromCheckpointHook

---

opennmt/runner.py

Do not require external evaluators when saving the evaluations preds

---

docs/serving.md

Fix typo in serving.md

---

docs/configuration.md
docs/inference.md
opennmt/layers/noise.py
opennmt/models/sequence_to_sequence.py

As in https://arxiv.org/abs/1808.09381

Support applying noise on the decoding output

---

CHANGELOG.md
opennmt/runner.py

Write external evaluators summaries in a separate directory

---

docs/configuration.md
opennmt/utils/optim.py

@atebbifakhr Can you look at this proposal? It requires to know the variable names but once the new parameter `freeze_variables` is set, the list of frozen and trainable variables will be logged for information/debugging.
Closes #450.

Add freeze_variables parameter

---

opennmt/utils/decoding.py

Fix beam search length_penalty bug

Fix beam search length_penalty bug

---

opennmt/utils/optim.py

reference to [https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/optimization.py#L86](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/optimization.py#L86)

Fix mixed precision training NAN and INF bug

---

opennmt/evaluation.py
opennmt/tests/evaluation_test.py

Add perplexity in evaluation metrics

---

docs/configuration.md
opennmt/evaluation.py
opennmt/models/model.py
opennmt/runner.py
opennmt/tests/evaluation_test.py
opennmt/tests/runner_test.py
opennmt/training.py

Automatic export on evaluation

---

opennmt/data/text.py
opennmt/tests/text_test.py

Support arbitrary spacer placement in tokens_to_words

---

opennmt/data/noise.py
opennmt/tests/noise_test.py
opennmt/tokenizers/tokenizer.py

Force tokenizers and noisers to run on CPU

---

opennmt/models/model.py
opennmt/tests/model_test.py

Fix error when creating model variables with guided alignment

---

opennmt/tests/losses_test.py
opennmt/utils/losses.py

Set reduction to support running GA loss under distribution strategy

---

opennmt/decoders/self_attention_decoder.py
opennmt/layers/transformer.py
opennmt/tests/decoder_test.py

Always return attention of the first source in Transformer decoder

---

opennmt/runner.py
opennmt/training.py

Get a batch per replica instead of relying on TF batch splitting logic

---

opennmt/tests/runner_test.py
opennmt/training.py

Skip last partial batch in multi GPU training on finite dataset

---

examples/library/README.md
examples/library/custom_transformer_training.py
examples/library/minimal_transformer_training.py

The existing example is moved to custom_transformer_training.py.

Replace minimal_transformer_training by a truly minimal example

---

opennmt/decoders/self_attention_decoder.py
opennmt/encoders/self_attention_encoder.py
opennmt/layers/transformer.py
opennmt/models/catalog.py
opennmt/models/transformer.py
opennmt/tests/transformer_test.py

Add relative position representations

---

examples/serving/python/ende_client.py

Convert numpy array to Python list before running detokenization

---

opennmt/data/vocab.py
opennmt/runner.py
opennmt/tests/runner_test.py
opennmt/tests/vocab_test.py
opennmt/utils/checkpoint.py

* Remove embedding distribution mirroring as it creates more issues  than it solves (frequent NaN loss)
* Fix iteration count in updated checkpoint
* Make update_vocab updates the Runner config for tasks chaining

Fixes for vocabulary update

---

opennmt/bin/ark_to_records.py

Pass Numpy dtype instead of TensorFlow dtype to Numpy function

---

opennmt/layers/rnn.py
opennmt/utils/misc.py
setup.py

Update to TensorFlow 2.1 and TensorFlow Addons 0.7

---

opennmt/bin/main.py
opennmt/config.py
opennmt/models/__init__.py
opennmt/models/catalog.py
opennmt/optimizers/__init__.py
opennmt/optimizers/utils.py
opennmt/schedules/__init__.py
opennmt/schedules/lr_schedules.py
opennmt/tests/config_test.py
opennmt/tests/lr_schedules_test.py
opennmt/tests/misc_test.py
opennmt/tests/optimizer_test.py
opennmt/tests/tokenizer_test.py
opennmt/tokenizers/__init__.py
opennmt/tokenizers/opennmt_tokenizer.py
opennmt/tokenizers/tokenizer.py
opennmt/utils/misc.py

* It prevents users from selecting unrelated classes or functions in a specific module.
* It allows users to register new classes that can be referenced by name in the configuration.
* It enables better error reporting by listing available classes.
This concerns models in the catalog, tokenizers, learning rate schedules, and optimizers.

Use a registration mechanism for classes selectable by name

---

opennmt/tests/optimizer_test.py

cf. https://github.com/tensorflow/tensorflow/commit/eea407993125ebca71d5d237a29e0147165177a7

Prepare for removal of values attribute from DistributedValues

---

opennmt/tests/training_test.py
opennmt/training.py
opennmt/utils/misc.py

cf. https://github.com/tensorflow/tensorflow/commit/19ac5f4f6c44ce98654f26c24bb8cd3971c821ab

Prepare for primary attribute of DistributedValues going private

---

opennmt/training.py

This saves a few computation for each training step.

Only compute gradients global norm when the value is actually recorded

---

README.md
docs/training.md
opennmt/bin/main.py
opennmt/models/model.py
opennmt/runner.py
opennmt/training.py
opennmt/utils/checkpoint.py

Add Horovod trainer

---

opennmt/utils/fmeasure.py
opennmt/utils/scorers.py
opennmt/utils/ter.py
opennmt/utils/wer.py
setup.py

Add new scorer to evaluate valid file while training.
these scorers are : Translation Edit Rate (TER), Word Error Rate (WER), f-measure, precision and recall (usefull for the seq2seq tagging model)

New scorers

---

opennmt/training.py

Do not report target tokens per second for unsupervised models

---

opennmt/bin/main.py

Fix error in onmt-main when using run types other than train

---

opennmt/inputters/inputter.py
opennmt/tests/inputter_test.py

This improves support of nested inputters and allows users to customize the filtering logic.

Move example filtering logic to the inputter class

---

opennmt/models/model.py
opennmt/tests/model_test.py

Fix serving function for language models

---

opennmt/tests/scorers_test.py
opennmt/utils/fmeasure.py

And remove some unused variables.
Fixes #655.

Improve robustness of PRFScorer

---

opennmt/runner.py
opennmt/tests/training_test.py
opennmt/training.py

Move more logic to the base Trainer class and make it implement single GPU training.

Further refactoring of Trainer classes

---

opennmt/layers/transformer.py
opennmt/tests/transformer_test.py

Fix undefined gradient shape in relative MultiHeadAttention

---

opennmt/tokenizers/tokenizer.py

In TensorFlow 2.3, tf.is_tensor() returns True on RaggedTensor.

Handle RaggedTensor first in detokenize method

---

opennmt/bin/main.py

Fix data_dir prefix when the data block contains non string values

---

opennmt/optimizers/utils.py

The behavior has changed in TensorFlow 2.3.

Do not synchronize accumulated gradients on assignments

---

opennmt/runner.py
opennmt/tests/runner_test.py
opennmt/tests/training_test.py
opennmt/training.py

As part of this change, the training statistics management is moved to a separate class to not make the training loop more complex.

Return a summary of the training from the train method

---

opennmt/data/noise.py
opennmt/data/text.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/inputter_test.py
opennmt/tests/model_test.py
opennmt/tests/noise_test.py
opennmt/tests/runner_test.py
opennmt/tests/text_test.py
opennmt/tests/tokenizer_test.py
opennmt/tests/vocab_test.py
opennmt/tokenizers/tokenizer.py

Remove file encoding declaration

---

docs/vocabulary.md

Clarify the different ways of generating the vocabularies.

Improve vocabulary documentation

---

opennmt/bin/build_vocab.py
opennmt/tests/tokenizer_test.py
opennmt/tokenizers/opennmt_tokenizer.py
opennmt/tokenizers/tokenizer.py

Related to https://github.com/OpenNMT/Tokenizer/issues/176.

Support pre-tokenization for SentencePiece training in build-vocab

---

opennmt/tests/training_test.py
opennmt/training.py

Another type fix to make the training summary JSON serializable

---

opennmt/inputters/text_inputter.py
opennmt/tests/inputter_test.py
opennmt/tests/training_test.py
opennmt/training.py

Log the ratio of OOV tokens in the training data and list the 10 most frequent OOV tokens.

Summarize OOV tokens at the end of the training

---

opennmt/models/__init__.py

This is causing small inconsistencies in the generated documentation.

Remove unused class alias

---

opennmt/training.py

This is equivalent, but it is usually easier to scale the loss directly.

Scale the loss not the gradients when aggregating multiple batches

---

opennmt/runner.py

Setting a mixed precision policy will initialize the GPU context and reserve all available memory. So this should be set after the batch size is autotuned.

Fix batch size autotuning with mixed precision

---

opennmt/bin/main.py

Improve log format when using onmt-main script

---

opennmt/decoders/decoder.py
opennmt/tests/model_test.py

Fix dtype error in RNN decoder with mixed precision

---

opennmt/evaluation.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/runner_test.py

Disable n_best when running evaluation

---

opennmt/data/dataset.py

No need to use TensorFlow functions here.

Simplify the normalization of dataset weights

---

opennmt/models/sequence_to_sequence.py

Fix encoding when writing sentence detokenized by an in-graph tokenizer

---

opennmt/decoders/decoder.py
opennmt/inputters/text_inputter.py
opennmt/layers/position.py
opennmt/models/model.py
opennmt/models/sequence_to_sequence.py
opennmt/tests/tflite_test.py
opennmt/utils/exporters.py

Allow layers to detect TensorFlow Lite tracing

---

opennmt/layers/common.py

This function is available since TensorFlow 2.4.

Replace custom implementation with tf.nn.gelu

---

CHANGELOG.md
README.md
docs/api_examples.md
docs/conf.py
docs/generate-apidoc.py
docs/index.rst
setup.py

Use the same generation script as CTranslate2.

Use simpler structure for the generated API reference

---

opennmt/data/dataset.py
opennmt/evaluation.py
opennmt/inference.py
opennmt/inputters/inputter.py
opennmt/models/language_model.py
opennmt/models/model.py
opennmt/tests/model_test.py
opennmt/training.py

Fix inference features returned by the language model inputter

---

opennmt/inputters/record_inputter.py
opennmt/tests/inputter_test.py

Fix dtype of SequenceRecordInputter's length feature

---

opennmt/runner.py

The memory usage should be the same whether we are accumulating 2 steps or N steps.

Use minimal gradient accumulation in batch size autotuning

---

opennmt/layers/transformer.py

The softmax op already accumulates values in FP32 so there should be no numerical issues in FP16.

Remove non needed FP32 cast before softmax

---

opennmt/tests/model_test.py
opennmt/utils/losses.py

Fix error when using guided alignment with mixed precision

---

docs/configuration.md
opennmt/tests/scorers_test.py
opennmt/utils/scorers.py

Added scorers for chrF and chrF++ metrics from sacrebleu since they are becoming more and more prevalent in the literature.

chrF and chrF++

---

opennmt/training.py

Fix #985 as suggested by @guillaumekln 
Successfully tested on a training with early stopping

Fixed issue with horovod and early stopping
